version: 0.2

phases:
  install:
    commands:
      # pulumi
      - curl -fsSL https://get.pulumi.com/ | sh
      - export PATH=$PATH:$HOME/.pulumi/bin
  build:
    commands:
      - npm install
      - npm run build
      - pulumi stack select dev
      - pulumi preview