
name: Preview with Pulumi

on:
  - [pull_request, push]

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      - uses: docker://pulumi/actions
        with:
          args: preview --stack dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr